In [2]:
import numpy as np


In [ ]:
# 1 руками через метод квадратов, в питоне:

In [7]:
matrices = [
    # 1
    np.array([[4, 0, 4, 5],
              [0, 1, 5, 6],
              [-2, 2, 2, 0],
              [1, -5, 1, 3]]),
    
    # 2
    np.array([[5, 0, 1, 3],
              [0, 1, 5, -1],
              [7, -1, 3, -2],
              [5, 3, 0, 1]]),
    
    # 3
    np.array([[4, 0, 1, 5],
              [1, 1, 0, 4],
              [0, 1, 1, 5],
              [6, -4, 1, 1]]),
    
    # 7
    np.array([[3, 2, 0, 1],
              [0, 2, 2, 3],
              [1, 5, 6, 1],
              [-2, 0, 3, 2]]),
    
    # 8
    np.array([[5, 1, 3, 0],
              [-3, 0, 5, 2],
              [2, 1, -1, 3],
              [1, 5, 0, 7]]),
    
    # 9
    np.array([[7, 6, 0, 1],
              [1, 3, 5, 0],
              [0, 1, -2, 4],
              [1, 1, 2, 3]]),
    
    # 13
    np.array([[2, 3, 0, 1],
              [-4, 0, 3, 1],
              [0, 8, 7, 5],
              [3, 3, 4, -2]]),
    
    # 14
    np.array([[3, 1, 3, 1],
              [2, 4, 2, 5],
              [1, 4, 5, 3],
              [-1, 0, 3, 2]]),
    
    # 15
    np.array([[7, 6, 0, 1],
              [1, 3, 5, 0],
              [0, 1, -2, 4],
              [1, 1, 2, 3]])
]

# Вычисляем определители
print("РЕЗУЛЬТАТЫ ВЫЧИСЛЕНИЯ ОПРЕДЕЛИТЕЛЕЙ:")
print("=" * 50)

for i, matrix in enumerate(matrices, 1):
    det = np.linalg.det(matrix)
    print(f"Матрица {i}:")
    print(f"Определитель = {det:.2f}")

    print("-" * 40)

РЕЗУЛЬТАТЫ ВЫЧИСЛЕНИЯ ОПРЕДЕЛИТЕЛЕЙ:
Матрица 1:
Определитель = 188.00
----------------------------------------
Матрица 2:
Определитель = -543.00
----------------------------------------
Матрица 3:
Определитель = 36.00
----------------------------------------
Матрица 4:
Определитель = 65.00
----------------------------------------
Матрица 5:
Определитель = 408.00
----------------------------------------
Матрица 6:
Определитель = -288.00
----------------------------------------
Матрица 7:
Определитель = -156.00
----------------------------------------
Матрица 8:
Определитель = 160.00
----------------------------------------
Матрица 9:
Определитель = -288.00
----------------------------------------


In [15]:
# 2

matrices = [
    # Вариант 1
    {
        'A': np.array([[1, 2, 4], [7, 5, -2], [-2, 1, 3]]),
        'B': np.array([[-1, 0, 3], [2, -6, 1], [-7, 1, 5]]),
        'C': np.array([[-2, 3], [4, 0], [7, -1]])
    },
    # Вариант 2
    {
        'A': np.array([[0, 3, 4], [-7, 1, -2], [2, -1, 3]]),
        'B': np.array([[1, 2, 4], [7, 0, -2], [-3, -2, 5]]),
        'C': np.array([[-3, 2], [0, 4], [-1, 7]])
    },
    # Вариант 3
    {
        'A': np.array([[5, 2, 9], [7, 0, -2], [-2, 1, 6]]),
        'B': np.array([[1, -2, 1], [7, 5, -2], [-2, 8, 3]]),
        'C': np.array([[-2, 3], [4, 5], [0, -1]])
    },
    # Вариант 4
    {
        'A': np.array([[1, -2, 8], [7, 5, -2], [-2, 3, 0]]),
        'B': np.array([[0, 2, 4], [1, -3, -2], [-2, 1, 3]]),
        'C': np.array([[0, 3], [5, -4], [7, -1]])
    },
    # Вариант 5
    {
        'A': np.array([[9, 2, 4], [7, 5, -5], [6, -2, 3]]),
        'B': np.array([[8, 2, 4], [0, 1, -3], [-2, 1, 6]]),
        'C': np.array([[-2, 0], [4, 8], [1, -1]])
    }
]

for i, matrices_set in enumerate(matrices, 1):
    print(f"\nВАРИАНТ {i}:")    
    A = matrices_set['A']
    B = matrices_set['B']
    C = matrices_set['C']
    
    # 1. A + B
    print("1. A + B =")
    print(A + B)
    
    # 2. B - A
    print("\n2. B - A =")
    print(B - A)
    
    # 3. A × C
    print("\n3. A × C =")
    print(np.dot(A, C))
    
    # 4. A × B × C
    print("\n4. A × B × C =")
    AB = np.dot(A, B)
    ABC = np.dot(AB, C)
    print(ABC)
    
    print("=" * 50)



ВАРИАНТ 1:
1. A + B =
[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]

2. B - A =
[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]

3. A × C =
[[34 -1]
 [-8 23]
 [29 -9]]

4. A × B × C =
[[ 193 -100]
 [ -50   35]
 [  92  -61]]

ВАРИАНТ 2:
1. A + B =
[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]

2. B - A =
[[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]

3. A × C =
[[ -4  40]
 [ 23 -24]
 [ -9  21]]

4. A × B × C =
[[ -41   84]
 [  22 -308]
 [  17  139]]

ВАРИАНТ 3:
1. A + B =
[[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]

2. B - A =
[[-4 -4 -8]
 [ 0  5  0]
 [ 0  7 -3]]

3. A × C =
[[ -2  16]
 [-14  23]
 [  8  -7]]

4. A × B × C =
[[ 286  335]
 [-142 -118]
 [ 242  250]]

ВАРИАНТ 4:
1. A + B =
[[ 1  0 12]
 [ 8  2 -4]
 [-4  4  3]]

2. B - A =
[[-1  4 -4]
 [-6 -8  0]
 [ 0 -2  3]]

3. A × C =
[[ 46   3]
 [ 11   3]
 [ 15 -18]]

4. A × B × C =
[[ 304 -150]
 [  69   27]
 [-163   75]]

ВАРИАНТ 5:
1. A + B =
[[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]

2. B - A =
[[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]

3. A × C =
[[ -6  12]
 [  1  45]
 [-17 -19]